services:
  neo4j-ollama:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=none  # Change username and password as needed
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama-container
    pull_policy: always
    tty: true
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=http://ollama-container:11434
    depends_on:
      - neo4j-ollama

  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - jupyter_data:/home/jovyan/work
    depends_on:
      - neo4j-ollama
      - ollama

volumes:
  neo4j_data:
  jupyter_data:
